# Create GitHub repository and seed it with initial structure

resource "github_repository" "app" {
  count = var.create_github_repo ? 1 : 0

  name        = var.app_name
  description = local.full_display_name
  visibility  = "private"

  auto_init = true
}

resource "github_repository_vulnerability_alerts" "app" {
  count      = var.create_github_repo ? 1 : 0
  repository = github_repository.app[0].name
}

# Deployment environments, keyed off the same github_environments list that
# drives the OIDC environment subjects in az-oidc.tf so the GitHub gate and
# the Azure claim can't drift apart. Only the environment's existence (what
# the OIDC claim needs) is guaranteed here — gate details (reviewers, wait
# timers, branch policies) are the app team's to configure in their repo.
# Like the other GitHub resources, only created when the repo itself is —
# for existing repos (create_github_repo = false) create the environment
# manually; the federated credential is still created either way.
resource "github_repository_environment" "app" {
  for_each = var.create_github_repo ? toset(var.github_environments) : toset([])

  repository  = github_repository.app[0].name
  environment = each.value

  # Create once, then hands off — app teams own gate details in their repo
  lifecycle {
    ignore_changes = all
  }
}

# Seed backend.tf for each guaranteed root module.
# No-env apps ("" → single root)  : infra/terraform/backend.tf        key = "terraform.tfstate"
# Env apps (["prod","dev"] etc.)   : infra/terraform/{env}/backend.tf  key = "{env}/terraform.tfstate"
#
# Nested key convention: mirrors the directory tree inside the blob container
# so devs can later add prod/network/terraform.tfstate without colliding with
# a flat "prod.terraform.tfstate" at the same level.
locals {
  backend_seeds = var.create_github_repo ? {
    for env in local.environments : (env == "" ? "root" : env) => {
      path = env == "" ? "infra/terraform/backend.tf" : "infra/terraform/${env}/backend.tf"
      key  = env == "" ? "terraform.tfstate" : "${env}/terraform.tfstate"
    }
  } : {}
}

resource "github_repository_file" "backend" {
  for_each = local.backend_seeds

  repository          = github_repository.app[0].name
  branch              = "main"
  file                = each.value.path
  overwrite_on_create = false
  commit_message      = "chore: seed ${each.value.path} [platform-iac]"

  content = <<-EOT
# Generated by the platform workload module
terraform {
  backend "azurerm" {
    resource_group_name  = "rg-platform-iac"
    storage_account_name = "contosoiaceastus2"
    container_name       = "${azurerm_storage_container.terraform_state.name}"
    key                  = "${each.value.key}"
    use_azuread_auth     = true
  }
}
EOT

  # Seed once, then hands off — dev changes in the app repo won't be reverted
  lifecycle {
    ignore_changes = [content]
  }
}
